/*
 * File: app/store/incidJsonStore.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CCIVIC.store.incidJsonStore', {
    extend: 'Ext.data.Store',
    requires: [
        'CCIVIC.model.Incidencia'
    ],

    config: {
        model: 'CCIVIC.model.Incidencia',
        storeId: 'incidJsonStore',
        proxy: {
            type: 'ajax',
            url: 'data/incidencia.json',
            writer: {
                type: 'json',
                root: 'incidencia'
            }
        }
    }
});