/*
 * File: app/store/IncidJSONStore.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CCIVIC.store.IncidJSONStore', {
    extend: 'Ext.data.Store',
    requires: [
        'CCIVIC.model.Incidencia'
    ],

    config: {
        model: 'CCIVIC.model.Incidencia',
        storeId: 'IncidJSONStore',
        proxy: {
            type: 'ajax',
            url: 'data/incidencia.json',
            reader: {
                type: 'json',
                rootProperty: 'incidencia'
            },
            writer: {
                type: 'json',
                rootProperty: 'incidencia'
            }
        }
    }
});