/*
 * File: app/view/Foto.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CCIVIC.view.Foto', {
    extend: 'Ext.Panel',

    config: {
        layout: {
            type: 'fit'
        },
        items: [
            {
                xtype: 'container',
                itemId: 'FotoContainer',
                items: [
                    {
                        xtype: 'image',
                        centered: true,
                        height: 320,
                        itemId: 'imgFoto',
                        width: 320
                    }
                ]
            },
            {
                xtype: 'toolbar',
                docked: 'bottom',
                itemId: 'fotoBar',
                items: [
                    {
                        xtype: 'button',
                        itemId: 'btnOk',
                        ui: 'round',
                        iconMask: true,
                        text: 'Acceptar'
                    },
                    {
                        xtype: 'button',
                        itemId: 'btnCapturar',
                        ui: 'round',
                        text: 'Capturar'
                    },
                    {
                        xtype: 'button',
                        itemId: 'btnSeleccionar',
                        ui: 'round',
                        text: 'Seleccionar'
                    }
                ]
            }
        ],
        listeners: [
            {
                fn: 'onBtnOkTap',
                event: 'tap',
                delegate: '#btnOk'
            },
            {
                fn: 'onBtnCapturarTap',
                event: 'tap',
                delegate: '#btnCapturar'
            },
            {
                fn: 'onBtnSeleccionarTap',
                event: 'tap',
                delegate: '#btnSeleccionar'
            },
            {
                fn: 'onPanelShow',
                event: 'show'
            }
        ]
    },

    onBtnOkTap: function(button, e, options) {
        var list = Ext.getCmp('incidList');

        list.refresh();
        this.getParent().pop();



    },

    onBtnCapturarTap: function(button, e, options) {
        var storeIncid = Ext.data.StoreManager.lookup('IncidStore');

        Ext.device.Camera.capture({
            success: function(img){        
                for(var i = 0; i < storeIncid.getCount(); i++) {          
                    if (storeIncid.getAt(i).get('IdCamp') == 'FOTO'){
                        storeIncid.getAt(i).set('ValorCamp1', img);           
                    } 
                }
                Ext.ComponentQuery.query('#imgFoto')[0].setSrc(img);       
                Ext.ComponentQuery.query('#imgFoto')[0].setHeight(320);       
                Ext.ComponentQuery.query('#imgFoto')[0].setWidth(320);       
            },
            scope: this,
            source: 'camera',
            destination: 'file',
            encoding: 'jpg'
        });

        storeIncid.sync();
    },

    onBtnSeleccionarTap: function(button, e, options) {
        var storeIncid = Ext.data.StoreManager.lookup('IncidStore');

        Ext.device.Camera.capture({
            success: function(img){        
                for(var i = 0; i < storeIncid.getCount(); i++) {          
                    if (storeIncid.getAt(i).get('IdCamp') == 'FOTO'){
                        storeIncid.getAt(i).set('ValorCamp1', img);           
                    } 
                }  
                Ext.ComponentQuery.query('#imgFoto')[0].setSrc(img);
                Ext.ComponentQuery.query('#imgFoto')[0].setHeight(320);       
                Ext.ComponentQuery.query('#imgFoto')[0].setWidth(320);       
            },
            scope: this,
            source: 'library',
            destination: 'file',
            encoding: 'jpg'
        });

        storeIncid.sync();
    },

    onPanelShow: function(component, options) {
        var storeIncid = Ext.data.StoreManager.lookup('IncidStore'), uri;

        for(var i = 0; i < storeIncid.getCount(); i++) {          
            if (storeIncid.getAt(i).get('IdCamp') == 'FOTO'){
                uri = storeIncid.getAt(i).get('ValorCamp1');           
            } 
        }

        Ext.ComponentQuery.query('#imgFoto')[0].setSrc(uri);    


    }

});