/*
 * File: app/view/Foto.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CCIVIC.view.Foto', {
    extend: 'Ext.Panel',

    config: {
        layout: {
            type: 'fit'
        },
        items: [
            {
                xtype: 'container',
                itemId: 'FotoContainer'
            },
            {
                xtype: 'toolbar',
                docked: 'bottom',
                itemId: 'fotoBar',
                items: [
                    {
                        xtype: 'button',
                        itemId: 'btnOk',
                        ui: 'round',
                        iconMask: true,
                        text: 'Acceptar'
                    },
                    {
                        xtype: 'button',
                        itemId: 'btnCapturar',
                        ui: 'round',
                        text: 'Capturar'
                    },
                    {
                        xtype: 'button',
                        itemId: 'btnSeleccionar',
                        ui: 'round',
                        text: 'Seleccionar'
                    }
                ]
            }
        ],
        listeners: [
            {
                fn: 'onBtnOkTap',
                event: 'tap',
                delegate: '#btnOk'
            },
            {
                fn: 'onBtnCapturarTap',
                event: 'tap',
                delegate: '#btnCapturar'
            },
            {
                fn: 'onBtnSeleccionarTap',
                event: 'tap',
                delegate: '#btnSeleccionar'
            },
            {
                fn: 'onPanelShow',
                event: 'show'
            }
        ]
    },

    onBtnOkTap: function(button, e, options) {
        var list = Ext.getCmp('incidList');

        list.refresh();
        this.getParent().pop();



    },

    onBtnCapturarTap: function(button, e, options) {
        var storeIncid = Ext.data.StoreManager.lookup('IncidStore');

        Ext.device.Camera.capture({
            success: function(img){                       
                var src = 'data:image/jpg;base64,' + img;
                var image = '<div align="center"><img src="' + src + '" vspace="10" height="65%" /></div>';

                for(var i = 0; i < storeIncid.getCount(); i++) {          
                    if (storeIncid.getAt(i).get('IdCamp') == 'FOTO'){                          
                        storeIncid.getAt(i).set('ValorCamp1', img);    
                        storeIncid.getAt(i).set('ValorImg', image);           
                    } 
                }                           
                Ext.ComponentQuery.query('#FotoContainer')[0].setHtml(image);
            },
            scope: this,
            source: 'camera',
            destination: 'data',
            encoding: 'jpg'       
        });

        storeIncid.sync();
    },

    onBtnSeleccionarTap: function(button, e, options) {
        var storeIncid = Ext.data.StoreManager.lookup('IncidStore');

        Ext.device.Camera.capture({
            success: function(img){                       
                var src = 'data:image/jpg;base64,' + img;
                var image = '<div align="center"><img src="' + src + '" vspace="10" height="65%" /></div>';

                for(var i = 0; i < storeIncid.getCount(); i++) {          
                    if (storeIncid.getAt(i).get('IdCamp') == 'FOTO'){                
                        storeIncid.getAt(i).set('ValorCamp1', img);    
                        storeIncid.getAt(i).set('ValorImg', image);           
                    } 
                }                         
                Ext.ComponentQuery.query('#FotoContainer')[0].setHtml(image);
            },
            scope: this,
            source: 'library',
            destination: 'data',
            encoding: 'jpg'
        });

        storeIncid.sync();
    },

    onPanelShow: function(component, options) {
        var storeIncid = Ext.data.StoreManager.lookup('IncidStore'), image;

        Ext.ComponentQuery.query('#FotoContainer')[0].setHtml('');

        for(var i = 0; i < storeIncid.getCount(); i++) {          
            if (storeIncid.getAt(i).get('IdCamp') == 'FOTO'){
                image = storeIncid.getAt(i).get('ValorImg');           
            } 
        }

        Ext.ComponentQuery.query('#FotoContainer')[0].setHtml(image);


    }

});