/*
 * File: app/view/navTemes.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Designer does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CCIVIC.view.navTemes', {
    extend: 'Ext.navigation.View',
    alias: 'widget.navtemes',

    config: {
        defaultBackButtonText: '\'Enrere\'',
        useTitleForBackButtonText: true,
        layout: {
            animation: false,
            type: 'card'
        },
        items: [
            {
                xtype: 'nestedlist',
                id: 'temesList',
                itemId: 'temesList',
                displayField: 'nom',
                store: 'temesTreeStore',
                title: 'Selecció de temes'
            }
        ],
        listeners: [
            {
                fn: 'onTemesListLeafItemTap',
                event: 'leafitemtap',
                delegate: '#temesList'
            },
            {
                fn: 'onNavigationviewShow',
                event: 'show'
            }
        ]
    },

    onTemesListLeafItemTap: function(nestedlist, list, index, target, record, e, options) {
        var tabPanel = Ext.create('CCIVIC.view.Incidencia',{fullscreen: true});

        //Es modifica el label amb el leaf seleccionat.
        Ext.ComponentQuery.query('#nomTema')[0].setHtml('Incidencia '+record.get('nom'));

        this.push(tabPanel);
    },

    onNavigationviewShow: function(component, options) {
        var store = Ext.data.StoreManager.lookup('PrefStore');

        if (store.getCount() === 0){
            Ext.Msg.alert('Avís:', 'Es necessari introduir les dades personals.');
            store.add(
            {IdPref:'NOM', CodiPref: 'Nom', ValorPref: '', Req: '*'},
            {IdPref:'COGNOM', CodiPref: 'Cognoms', ValorPref: '', Req: '*'},
            {IdPref:'NUMDOC', CodiPref: 'Número de document', ValorPref: '', Req: '*'},
            {IdPref:'TEL', CodiPref: 'Mòbil', ValorPref: '', Req:' '},
            {IdPref:'EMAIL', CodiPref: 'Adreça electrònica', ValorPref: '', Req: ' '});

            var Panel= Ext.create('CCIVIC.view.Dades',{fullscreen: true});
            this.push(Panel);
        }
    }

});