/*
 * File: app/view/NavView.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Designer does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.NavView', {
    extend: 'Ext.navigation.View',
    alias: 'widget.navview',

    config: {
        navigationBar: {
            id: 'navbar',
            itemId: 'NavBar',
            title: 'Bústia Ciutadana'
        },
        items: [
            {
                xtype: 'formpanel',
                id: 'dadespersonals',
                itemId: 'DadesPersonals',
                title: 'Dades personals',
                items: [
                    {
                        xtype: 'label',
                        cls: [
                            ''
                        ],
                        html: 'Nom (*)',
                        id: 'lbnom',
                        itemId: 'lbNom',
                        ui: ''
                    },
                    {
                        xtype: 'textfield',
                        height: 21,
                        id: 'nom',
                        itemId: 'Nom',
                        label: '',
                        name: '',
                        required: true
                    },
                    {
                        xtype: 'label',
                        html: 'Cognoms (*)',
                        id: 'lbcognoms',
                        itemId: 'lbCognoms'
                    },
                    {
                        xtype: 'textfield',
                        id: 'cognoms',
                        itemId: 'Cognoms',
                        labelWidth: 90,
                        required: true
                    },
                    {
                        xtype: 'label',
                        html: 'Tipus document (*)',
                        id: 'lbtipusdocument',
                        itemId: 'lbTipusDocument'
                    },
                    {
                        xtype: 'selectfield',
                        label: '',
                        name: 'tipusDocument',
                        required: true,
                        options: [
                            {
                                text: 'NIF',
                                value: 'NIF'
                            },
                            {
                                text: 'NIE',
                                value: 'NIE'
                            }
                        ]
                    },
                    {
                        xtype: 'label',
                        html: 'Núm. document (*)',
                        id: 'lbNumDoc',
                        itemId: 'lbNumDoc'
                    },
                    {
                        xtype: 'textfield',
                        id: 'numdocument',
                        itemId: 'NumDocument',
                        required: true
                    },
                    {
                        xtype: 'label',
                        html: 'Enviar la resposta a...',
                        id: 'lbresp',
                        itemId: 'lbResp'
                    },
                    {
                        xtype: 'selectfield',
                        id: 'resposta',
                        itemId: 'Resposta',
                        options: [
                            {
                                text: 'E-mail',
                                value: 'EMAIL'
                            },
                            {
                                text: 'Telèfon',
                                value: 'TEL'
                            },
                            {
                                text: 'Sense Resposta',
                                value: 'SR'
                            }
                        ]
                    },
                    {
                        xtype: 'label',
                        cls: [
                            ''
                        ],
                        html: 'Contacte',
                        id: 'lbcontacte',
                        itemId: 'lbContacte'
                    },
                    {
                        xtype: 'textfield'
                    },
                    {
                        xtype: 'button',
                        id: 'grabar',
                        itemId: 'Grabar',
                        text: 'Grabar'
                    }
                ]
            }
        ],
        listeners: [
            {
                fn: 'onGrabarTap',
                event: 'tap',
                delegate: '#grabar'
            }
        ]
    },

    onGrabarTap: function(button, e, options) {

    }

});