/*
 * File: app/view/NavView.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Designer does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CCIVIC.view.NavView', {
    extend: 'Ext.navigation.View',
    alias: 'widget.navview',

    config: {
        navigationBar: {
            id: 'navBar',
            itemId: 'NavBar'
        },
        items: [
            {
                xtype: 'container',
                itemId: 'listContainer',
                ui: '',
                layout: {
                    type: 'fit'
                },
                items: [
                    {
                        xtype: 'list',
                        itemId: 'prefList',
                        ui: 'round',
                        itemTpl: [
                            '<div>{CodiPref}:  {ValorPref}</div>'
                        ],
                        store: 'PrefStore',
                        grouped: false,
                        onItemDisclosure: true
                    },
                    {
                        xtype: 'button',
                        docked: 'bottom',
                        id: 'btnGrabar',
                        itemId: 'BtnGrabar',
                        text: 'Grabar'
                    }
                ]
            }
        ],
        listeners: [
            {
                fn: 'onPrefListItemTap',
                event: 'itemtap',
                delegate: '#prefList'
            },
            {
                fn: 'onBtnGrabarTap',
                event: 'tap',
                delegate: '#btnGrabar'
            },
            {
                fn: 'onNavigationviewShow',
                event: 'show'
            }
        ]
    },

    onPrefListItemTap: function(dataview, index, target, record, e, options) {
        Ext.Msg.prompt('Dades personals', record.get('CodiPref')+':', function(btn,text) {    
            if (btn == 'ok'){        
                record.set('ValorPref', text);                
            }       
        });


    },

    onBtnGrabarTap: function(button, e, options) {
        var store = Ext.data.StoreManager.lookup('PrefStore');
        store.sync();
    },

    onNavigationviewShow: function(component, options) {
        var store = Ext.data.StoreManager.lookup('PrefStore');

        if (store.getCount() === 0){
            store.add(
            {CodiPref: 'Nom', ValorPref: ''},
            {CodiPref: 'Cognoms', ValorPref: ''},
            {CodiPref: 'Tipus de document', ValorPref: ''},
            {CodiPref: 'Número de document', ValorPref: ''},
            {CodiPref: 'Enviar resposta a...', ValorPref: ''},
            {CodiPref: 'Mòbil', ValorPref: ''},
            {CodiPref: 'Adreça electrònica', ValorPref: ''});
        }
    }

});